export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).send('Only POST requests allowed');
  }

  const { text } = req.body;

  try {
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${process.env.OPENAI_API_KEY}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: "gpt-4",
        messages: [
          { role: "system", content: "You are an AI detector." },
          { role: "user", content: `Give a percentage confidence (0 to 100) that this LinkedIn post was generated by AI. Just return the number.\n\n"${text}"` }
        ],
        max_tokens: 10,
        temperature: 0.3
      })
    });

    const data = await response.json();
    const reply = data.choices[0].message.content.trim();
    const confidence = parseInt(reply.replace(/[^0-9]/g, ''), 10);
    res.status(200).json({ confidence: isNaN(confidence) ? -1 : confidence });
  } catch (error) {
    console.error("API Error:", error);
    res.status(500).json({ confidence: -1, error: "Internal Server Error" });
  }
}
